---
title: "Response To Reviewer Hadley"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> I really like it

OUR RESPONSE: Thanks for the feedback! 


## Overall 


> I'd recommend spending a little time thinking a slightly more political term than "fragile"

OUR RESPONSE: We have refined our introduction of "fragile" and introduced the idea of brittle software.

> I'm a bit worried this is over the page limit that we promised TAS (3-5 pages). We don't need to deal with this now but we will need to think about it for TAS.

OUR RESPONSE: We'd be glad to consider making some of the material available as a supplementary resource.

## Major comments

> This silently makes a missing value:
```
factor("a", levels = "c")
```
> Maybe worth a mention? (in "Compact but fragile")

OUR RESPONSE: We've added this into the initial problems with factors section.
     
> Another gotcha is that if you have strings that with non-ASCII characters, the default of order levels may vary from locale to locale.

OUR RESPONSE: We have woven this into the "Compact but fragile" section.

> I'm not sure if this can go anyway in the paper, but I realised in some sense you never visualise character strings, you always visualise factors. (i.e. you only see what's in the data, not the infinity of other possible values)

OUR RESPONSE: XX AM to think about?

> I think you should mention factors are right for models because you can't make predictions about factors that you didn't observe in the training data

OUR RESPONSE: XX AM to address?

> Would be nice to have link to paper in README and markdown version of paper for easy preview on GitHub. Should the paper be in the root directory?

OUR RESPONSE: Fixed

## Minor comments


> 1-37: "line or column" -> "row or column" ?

OUR RESPONSE: We've made this change.

> "uses hashed versions" -> more correct would be "uses a global string pool, so each unique string is only stored once"

OUR RESPONSE: We've made this change.

> Maybe make GSS variable names a bit more concise? Would shorten up the code chunks

OUR RESPONSE: Fixed

> 6-130: some of the quotes are around the wrong way

OUR RESPONSE: I've fixed many of these (note that they should be now all back-quote string quote)


